plugins:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "lib/proscenium/ext/**/*"
    - "fixtures/dummy/node_modules/**/*"
    - "fixtures/dummy/vendor/**/*"
    - "fixtures/external/**/*"
    - "gemfiles/**/*"

Layout/LineLength:
  Max: 100

Lint/ConstantDefinitionInBlock:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Style/CaseEquality:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/NegatedIf:
  Enabled: false

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Minitest/MultipleAssertions:
  Enabled: false
