// Registers Proscenium's Bun plugin, so `bun test` can import the same JS, TS, JSX and CSS your
// Rails app serves. Generated by `rails generate proscenium:bun`.
//
// Everything of substance lives in the gem, so this file should not need to change when
// Proscenium does.
//
// Keep this LAST in bunfig.toml's `preload` list. The plugin claims every uncached JS module, so
// anything that has to come from node_modules - a DOM shim, a testing library - must already be
// imported and cached by an earlier preload, or it gets fetched from your Rails app instead.

// Written to a file rather than read off a pipe, because a pipe cannot be relied on from here.
// Once happy-dom's GlobalRegistrator has run and a DOM-touching package has been imported - which
// is the normal state of a preload that comes before this one - every `Bun.spawn`/`Bun.spawnSync`
// in the process returns a zero-length stdout: exit status 0, empty stderr, no bytes, for any
// command at all.
const gemDirFile = `${process.env.TMPDIR ?? "/tmp"}/proscenium-gem-dir-${process.pid}`;

Bun.spawnSync(["bundle", "exec", "ruby", "-e", "print Gem.loaded_specs['proscenium'].gem_dir"], {
  stdout: Bun.file(gemDirFile),
  stderr: "inherit",
});

const gemDir = (await Bun.file(gemDirFile).text()).trim();
await Bun.file(gemDirFile).unlink();

if (!gemDir) {
  throw new Error(
    "could not locate the proscenium gem. `bundle exec ruby -e \"print " +
      "Gem.loaded_specs['proscenium'].gem_dir\"` produced nothing - its stderr is above.",
  );
}

const { register } = await import(`${gemDir}/lib/proscenium/runtime/bootstrap.js`);

await register();
