# frozen_string_literal: true

require 'digest'
require 'json'

module Proscenium
  # A participating gem's dependency context (#154): its package.json through the
  # `dependency-context-v1` projection, which keeps installation metadata only and is committed at
  # `.proscenium/packages/<gem>/package.json`.
  #
  # The one owner of the projection and its hash, shared by the CLI and the engine, so it must not
  # load ActiveSupport or anything else the CLI may not.
  module DependencyContext
    PROJECTION = 'dependency-context-v1'

    # The manifest fields a context keeps, in the order it writes them. Everything else (scripts,
    # devDependencies, version, entry points, workspaces) is left in the gem's own package.json.
    FIELDS = %w[dependencies peerDependencies peerDependenciesMeta optionalDependencies engines os
                cpu libc].freeze

    module_function

    def name_for(gem) = "@rubygems/#{gem}"

    def description_for(gem)
      "Generated by Proscenium from the #{gem} gem. Do not edit; " \
        'run bundle exec proscenium install.'
    end

    # The context for `gem` from its parsed `manifest`. An empty field is left out, as an absent
    # one is: the two install the same, so they hash the same.
    def project(gem, manifest)
      fields = FIELDS.each_with_object({}) do |key, kept|
        value = manifest[key]
        kept[key] = value unless value.nil? || (value.respond_to?(:empty?) && value.empty?)
      end

      { 'name' => name_for(gem), 'private' => true, 'description' => description_for(gem),
        **fields,
        'proscenium' => { 'projection' => PROJECTION, 'projectionSha256' => digest(gem, fields) } }
    end

    # The bytes committed for a context: fixed key order, two-space indent, a trailing newline, and
    # nothing that varies by host or time.
    def to_json(context) = "#{JSON.pretty_generate(context)}\n"

    # The projection hash. It hashes a fixed-field encoding of the projected fields, not JSON, so
    # it does not move with the json gem's output, key order, whitespace or escaping, and an edit
    # to anything the projection drops leaves it alone.
    def digest(gem, fields)
      Digest::SHA256.hexdigest("#{PROJECTION}\n#{encode(name_for(gem))}#{encode(fields)}")
    end

    # A self-delimiting encoding: a type tag, a length where there is one, then the value. Hash
    # keys are sorted by their bytes, so key order in the manifest does not matter; array order
    # does, as it does to npm.
    def encode(value)
      case value
      when String then "s#{value.bytesize}:#{value.b}"
      when true then 't'
      when false then 'f'
      when nil then 'n'
      when Integer then "i#{value};"
      when Float then "d#{value};"
      when Array then "a#{value.size}:#{value.map { encode(it) }.join}"
      when Hash
        pairs = value.sort_by { |key, _| key.to_s.b }
        "h#{value.size}:#{pairs.map { |key, val| encode(key.to_s) + encode(val) }.join}"
      else
        raise ArgumentError, "cannot encode #{value.class} in a dependency context"
      end
    end
  end
end
