// Registers Proscenium's Bun plugin, so `bun test` can import the same JS, TS, JSX and CSS your
// Rails app serves. Generated by `rails generate proscenium:bun`.
//
// Everything of substance lives in the gem, so this file should not need to change when
// Proscenium does.

const gemDir = (
  await Bun.spawn(["bundle", "exec", "ruby", "-e", "print Gem.loaded_specs['proscenium'].gem_dir"], {
    stdout: "pipe",
    stderr: "inherit",
  }).stdout.text()
).trim();

const { register } = await import(`${gemDir}/lib/proscenium/runtime/bootstrap.js`);

await register();
