# frozen_string_literal: true

require_relative 'helper'
require 'proscenium/dependency_context'

# The projection and its hash. The hashes below are golden vectors, computed by an independent
# implementation of the encoding as well as this one: a change to any of them changes every
# committed context in every app, so it must be deliberate, named in the CHANGELOG, and come with a
# new projection version.
describe Proscenium::DependencyContext do
  DC = Proscenium::DependencyContext

  def sha(manifest, gem: 'widget') = DC.project(gem, manifest).dig('proscenium', 'projectionSha256')

  BASE = { 'dependencies' => { 'ms' => '^2.1.3', 'clsx' => '^2.1.1' },
           'peerDependencies' => { 'react' => '^18.3.1' } }.freeze

  it 'pins the hash of a typical manifest' do
    assert_equal '6a55b2477c46b1c88a17c0130a1e09623d7c6006fdd9787328e1afc31a200b71', sha(BASE)
  end

  it 'keeps the gem name in the hash' do
    refute_equal sha(BASE), sha(BASE, gem: 'other')
  end

  it 'ignores key order' do
    reordered = { 'peerDependencies' => { 'react' => '^18.3.1' },
                  'dependencies' => { 'clsx' => '^2.1.1', 'ms' => '^2.1.3' } }

    assert_equal sha(BASE), sha(reordered)
  end

  it 'ignores every field the projection drops' do
    noisy = BASE.merge('name' => '@rubygems/widget', 'version' => '1.2.3', 'main' => 'index.js',
                       'exports' => { '.' => './index.js' }, 'scripts' => { 'build' => 'x' },
                       'devDependencies' => { 'eslint' => '^9' }, 'workspaces' => ['a'],
                       'packageManager' => 'pnpm@10.0.0', 'files' => ['dist'])

    assert_equal sha(BASE), sha(noisy)
  end

  # C16: policy belongs to the app. A gem's overrides, resolutions, pnpm settings, patches and
  # engine strictness never reach its context; its engines range does, as information.
  it "drops a gem's own install policy, and keeps its engines" do
    policy = { 'overrides' => { 'ms' => '1.0.0' }, 'resolutions' => { 'ms' => '1.0.0' },
               'pnpm' => { 'overrides' => { 'ms' => '1.0.0' } },
               'patchedDependencies' => { 'ms@2.1.3' => 'patches/ms.patch' },
               'engineStrict' => true, 'engines' => { 'node' => '>= 20' } }
    context = Proscenium::DependencyContext.project('widget', BASE.merge(policy))

    assert_empty context.keys & %w[overrides resolutions pnpm patchedDependencies engineStrict]
    assert_equal({ 'node' => '>= 20' }, context['engines'])
  end

  it 'treats an empty field as an absent one' do
    assert_equal sha(BASE), sha(BASE.merge('optionalDependencies' => {}, 'os' => []))
  end

  it 'changes with any dependency' do
    changed = BASE.merge('dependencies' => { 'ms' => '^2.1.2', 'clsx' => '^2.1.1' })

    refute_equal sha(BASE), sha(changed)
  end

  it 'keeps array order, as npm does' do
    one = sha(BASE.merge('os' => %w[darwin linux]))

    refute_equal one, sha(BASE.merge('os' => %w[linux darwin]))
  end

  it 'pins escapes, unicode and nested metadata' do
    manifest = { 'dependencies' => { 'quote"back\\slash' => "line\nbreak", 'ünïcode' => '✓' },
                 'peerDependenciesMeta' => { 'react' => { 'optional' => true } },
                 'engines' => { 'node' => '>=22' } }

    assert_equal '74ba3135e79c04a66ae86a083c56dd7384ef8652fafc11984310482dfe8d7d78', sha(manifest)
  end

  it 'is the same for a manifest read with CRLF line endings' do
    json = JSON.pretty_generate(BASE)

    assert_equal sha(JSON.parse(json)), sha(JSON.parse(json.gsub("\n", "\r\n")))
  end

  it 'writes the context in a fixed order with a trailing newline' do
    context = DC.project('widget', BASE.merge('version' => '9', 'scripts' => { 'x' => 'y' }))

    assert_equal <<~JSON, DC.to_json(context)
      {
        "name": "@rubygems/widget",
        "private": true,
        "description": "Generated by Proscenium from the widget gem. Do not edit; run bundle exec proscenium install.",
        "dependencies": {
          "ms": "^2.1.3",
          "clsx": "^2.1.1"
        },
        "peerDependencies": {
          "react": "^18.3.1"
        },
        "proscenium": {
          "projection": "dependency-context-v1",
          "projectionSha256": "#{sha(BASE)}"
        }
      }
    JSON
  end
end
