# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.2'

gem 'gems'
gem 'htmlbeautifier'
gem 'phlexible'
gem 'phlex-markdown', github: 'phlex-ruby/phlex-markdown'
gem 'proscenium', path: '../'
gem 'puma'
gem 'rails', '~> 8.0'
gem 'rouge'

group :development, :test do
  gem 'amazing_print'
  gem 'debug'
end

group :development do
  gem 'rubocop-minitest', require: false
  gem 'rubocop-packaging', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rake', require: false
  gem 'web-console'
end
