# frozen_string_literal: true

require 'digest'
require 'fileutils'
require 'json'

module StageA
  # Hand-written dependency contexts: a gem's package.json through the dependency-context-v1
  # projection, written to `.proscenium/packages/<gem>/package.json`. Stage B's CLI replaces this.
  module Context
    FIELDS = %w[dependencies peerDependencies peerDependenciesMeta optionalDependencies engines os
                cpu libc].freeze

    module_function

    # `projectionSha256` is provisional, over canonical JSON: the plan's fixed-field encoding
    # arrives with Stage B.
    def project(gem, manifest)
      context = { 'name' => "@rubygems/#{gem}", 'private' => true }
      FIELDS.each { |key| context[key] = manifest[key] if manifest[key]&.any? }
      sha = Digest::SHA256.hexdigest(JSON.generate(context.sort.to_h))
      context['description'] = "Generated by Proscenium from the #{gem} gem. Do not edit; run " \
                               'bundle exec proscenium install.'
      context['proscenium'] = { 'projection' => 'dependency-context-v1', 'projectionSha256' => sha }
      context
    end

    # Writes the context for `gem`, installed at `root`, into the app at `app`. Returns its
    # directory.
    def write(app, gem, root)
      dir = File.join(app, '.proscenium', 'packages', gem)
      FileUtils.mkdir_p(dir)
      manifest = JSON.parse(File.read(File.join(root, 'package.json')))
      json = JSON.pretty_generate(project(gem, manifest))
      File.write(File.join(dir, 'package.json'), "#{json}\n")
      dir
    end

    # The one-time registration: pnpm's workspace file listing every context.
    def register_pnpm(app)
      File.write(File.join(app, 'pnpm-workspace.yaml'), "packages:\n  - .proscenium/packages/*\n")
    end
  end
end
