# frozen_string_literal: true

require 'digest'
require 'fileutils'
require 'json'

module StageA
  # Hand-written dependency contexts: a gem's package.json through the dependency-context-v1
  # projection, written to `.proscenium/packages/<gem>/package.json`. Stage B's CLI replaces this.
  module Context
    FIELDS = %w[dependencies peerDependencies peerDependenciesMeta optionalDependencies engines os
                cpu libc].freeze
    PROJECTION = 'dependency-context-v1'

    module_function

    # `projectionSha256` is provisional, over canonical JSON: the plan's fixed-field encoding
    # arrives with Stage B.
    def project(gem, manifest, projection: PROJECTION)
      context = { 'name' => "@rubygems/#{gem}", 'private' => true }
      FIELDS.each { |key| context[key] = manifest[key] if manifest[key]&.any? }
      sha = Digest::SHA256.hexdigest(JSON.generate(context.sort.to_h))
      context['description'] = "Generated by Proscenium from the #{gem} gem. Do not edit; run " \
                               'bundle exec proscenium install.'
      context['proscenium'] = { 'projection' => projection, 'projectionSha256' => sha }
      context
    end

    # Writes the context for `gem`, installed at `root`, into the app at `app`. Returns its
    # directory.
    def write(app, gem, root)
      dir = File.join(app, '.proscenium', 'packages', gem)
      FileUtils.mkdir_p(dir)
      manifest = JSON.parse(File.read(File.join(root, 'package.json')))
      json = JSON.pretty_generate(project(gem, manifest))
      File.write(File.join(dir, 'package.json'), "#{json}\n")
      dir
    end

    PATTERN = '.proscenium/packages/*'

    # What a frozen install would refuse, from committed files and the installed gems alone: the
    # registration, each participating gem's context (missing, from another projection version,
    # or stale against its installed manifest), and contexts no participating gem owns. `roots`
    # maps each participating gem to its installed root. Nothing here needs a receipt.
    def drift(app, roots, projection: PROJECTION)
      problems = []
      problems << 'registration missing' unless registered?(app)
      roots.each do |gem, root|
        path = File.join(app, '.proscenium', 'packages', gem, 'package.json')
        next problems << "#{gem}: no context" unless File.exist?(path)

        committed = JSON.parse(File.read(path))['proscenium']
        manifest = JSON.parse(File.read(File.join(root, 'package.json')))
        current = project(gem, manifest, projection:)['proscenium']
        if committed['projection'] != projection
          problems << "#{gem}: projection changed from #{committed['projection']} to #{projection}"
        elsif committed['projectionSha256'] != current['projectionSha256']
          problems << "#{gem}: stale"
        end
      end
      contexts = File.join(app, '.proscenium', 'packages')
      orphans = Dir.exist?(contexts) ? Dir.children(contexts) - roots.keys : []
      problems + orphans.sort.map { "#{it}: orphaned context" }
    end

    def registered?(app)
      yaml = File.join(app, 'pnpm-workspace.yaml')
      package = File.join(app, 'package.json')
      (File.exist?(yaml) && File.read(yaml).include?(PATTERN)) ||
        (File.exist?(package) && File.read(package).include?(PATTERN))
    end

    # The one-time registration: the context pattern in pnpm's workspace file, spliced into an
    # existing one as text so its settings and comments survive (the plan's textual splice).
    def register_pnpm(app)
      path = File.join(app, 'pnpm-workspace.yaml')
      text = File.exist?(path) ? File.read(path) : ''
      return if text.include?(PATTERN)

      text = if (flow = text.match(/^packages:[ \t]*\[(?<list>[^\]]*)\](?<rest>.*)$/))
               # An inline list: `packages: ["apps/*"]`.
               list = [flow[:list].strip, "'#{PATTERN}'"].reject(&:empty?).join(', ')
               text.sub(flow[0], "packages: [#{list}]#{flow[:rest]}")
             elsif text.match?(/^packages:[ \t]*(#.*)?$/)
               text.sub(/^packages:[ \t]*(#.*)?\n/) { "#{it}  - #{PATTERN}\n" }
             else
               "packages:\n  - #{PATTERN}\n#{"\n" unless text.empty?}#{text}"
             end
      File.write(path, text)
    end
  end
end
