name: main
on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  go-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      GOWORK: off
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - run: go test ./test

  ruby-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rails: [rails-7.1, rails-7.2, rails-8, rails-8.1]
    runs-on: ${{ matrix.os }}
    env:
      RAILS_ENV: test
      GOWORK: off
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: go build -mod=readonly -buildmode=c-shared -o lib/proscenium/ext/proscenium main.go
      - run: bundle exec appraisal install
      - run: bundle exec appraisal ${{ matrix.rails }} bin/test

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rubocop -P --fail-level C
