name: main
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        ruby-version:
          - "3.3"
          - "head"

    runs-on: ${{ matrix.os }}

    env:
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
      - run: go version
      - run: go test ./test

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
      - run: bundle exec rake compile:local
      - run: bundle exec sus

  rubocop:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop -P --fail-level C
